version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: parkinglot-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: parking
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: parking_user
      MYSQL_PASSWORD: parking_pass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: parkinglot-prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - db

  grafana:
    image: grafana/grafana:9.0.0
    container_name: parkinglot-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  db_data:
